input_gain:
  enabled: true
  L: -0.873732388
  R: -0.873732388
input_level:
  enabled: true
stereo_enhance:
  enabled: false
agc_params:
  enabled: true
  mute_lo: false
  mute_hi: false
  drive: 13
  target: -12
  release_master: 30
  release_bass: 30
  gate_thresh: -24
  bass_coupling: 0.25
  window_size: -6
  window_release: 60
  ratio: 100000
  bass_thresh: 0
  idle_gain: 0
  attack_master: 0.200000003
  attack_bass: 0.200000003
hf_enhance:
  enabled: false
multiband_crossover:
  enabled: true
multiband_params:
  enabled: true
  drive: 8
  gate_thresh: -60
  limiters_enabled: true
  master_post_gain: 0
  band1_solo: false
  band1_mute: false
  band2_solo: false
  band2_mute: false
  band3_solo: false
  band3_mute: false
  band4_solo: false
  band4_mute: false
  band5_solo: false
  band5_mute: false
  band1_comp_lim_offset: -10
  band2_comp_lim_offset: -10
  band3_comp_lim_offset: -10
  band4_comp_lim_offset: -10
  band5_comp_lim_offset: -10
  compressors:
    band1_compressor_enabled: true
    band2_compressor_enabled: true
    band3_compressor_enabled: true
    band4_compressor_enabled: true
    band5_compressor_enabled: true
    band34_coupling: 0.300000012
    band45_coupling: 0.300000012
    band32_coupling: 0.300000012
    band23_coupling: 0.300000012
    band21_coupling: 0.300000012
    bands:
      - band: 1
        target: -40
        release: 0.129999995
        ratio: 1.29999995
        attack: 0.109999999
      - band: 2
        target: -45
        release: 0.0599999987
        ratio: 1.29999995
        attack: 0.0500000007
      - band: 3
        target: -45
        release: 0.0500000007
        ratio: 1.29999995
        attack: 0.0250000004
      - band: 4
        target: -45
        release: 0.0250000004
        ratio: 1.29999995
        attack: 0.0125000002
      - band: 5
        target: -45
        release: 0.0120000001
        ratio: 1.29999995
        attack: 0.00600000005
  limiters:
    band1_limiter_enabled: true
    band2_limiter_enabled: true
    band3_limiter_enabled: true
    band4_limiter_enabled: true
    band5_limiter_enabled: true
    bands:
      - band: 1
        target: -26
        release: 0.0250000004
        ratio: 6
        attack: 0.109999999
      - band: 2
        target: -23
        release: 0.0599999987
        ratio: 12
        attack: 0.0500000007
      - band: 3
        target: -23
        release: 0.0500000007
        ratio: 3
        attack: 0.0250000004
      - band: 4
        target: -23
        release: 0.0250000004
        ratio: 3
        attack: 0.0130000003
      - band: 5
        target: -23
        release: 0.0120000001
        ratio: 6
        attack: 0.00600000005