audio_devices:
  input:
    device_name: UNKNOWN
    device_id: 0
    device_uid: UNKNOWN
  output:
    device_name: UNKNOWN
    device_id: 0
    device_uid: UNKNOWN
input_gain:
  enabled: true
  L: 0.678274393
  R: 0.678274393
input_level:
  enabled: true
stereo_enhance:
  enabled: true
  drive: 1.22000003
agc_params:
  enabled: true
  mute_lo: false
  mute_hi: false
  drive: 6
  thresh: -14
  release_master: 20
  release_bass: 25
  gate_thresh: -28
  bass_coupling: 0.200000003
  window_size: -6
  window_release: 60
  ratio: 1000000
  bass_thresh: 0
  idle_gain: 0
  attack_master: 3
  attack_bass: 4
  bass_knee_type: soft
  bass_knee_width: 9
  master_knee_type: soft
  master_knee_width: 9
  bass_makeup_gain_mode: manual
  bass_makeup_gain: 0
  master_makeup_gain_mode: manual
  master_makeup_gain: 0
hf_enhance:
  enabled: false
multiband_crossover:
  enabled: true
multiband_params:
  enabled: true
  drive: 12
  gate_thresh: -36
  limiters_enabled: true
  master_post_gain: 6
  band1_solo: false
  band1_mute: false
  band2_solo: false
  band2_mute: false
  band3_solo: false
  band3_mute: false
  band4_solo: false
  band4_mute: false
  band5_solo: false
  band5_mute: false
  band1_comp_lim_offset: 0
  band2_comp_lim_offset: 0
  band3_comp_lim_offset: 0
  band4_comp_lim_offset: 0
  band5_comp_lim_offset: 0
  compressors:
    band1_compressor_enabled: true
    band2_compressor_enabled: true
    band3_compressor_enabled: true
    band4_compressor_enabled: true
    band5_compressor_enabled: true
    band34_coupling: 0.200000003
    band45_coupling: 0.200000003
    band32_coupling: 0.200000003
    band23_coupling: 0.200000003
    band21_coupling: 0.200000003
    bands:
      - band: 1
        thresh: -30
        gate_thresh: -36
        release: 0.100000001
        ratio: 1.29999995
        attack: 0.125
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 2
        thresh: -30
        gate_thresh: -36
        release: 0.100000001
        ratio: 1.29999995
        attack: 0.0900000036
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 3
        thresh: -30
        gate_thresh: -36
        release: 0.0399999991
        ratio: 1.29999995
        attack: 0.0299999993
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 4
        thresh: -30
        gate_thresh: -36
        release: 0.00499999989
        ratio: 1.29999995
        attack: 0.00300000003
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 5
        thresh: -30
        gate_thresh: -36
        release: 0.000500000024
        ratio: 1.29999995
        attack: 9.99999975e-05
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
  limiters:
    band1_limiter_enabled: true
    band2_limiter_enabled: true
    band3_limiter_enabled: true
    band4_limiter_enabled: true
    band5_limiter_enabled: true
    bands:
      - band: 1
        thresh: -22
        gate_thresh: -60
        release: 0.0500000007
        ratio: 12
        attack: 0.0799999982
        knee_type: soft
        knee_width: 3
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 2
        thresh: -22
        gate_thresh: -60
        release: 0.0500000007
        ratio: 12
        attack: 0.0900000036
        knee_type: soft
        knee_width: 3
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 3
        thresh: -22
        gate_thresh: -60
        release: 0.0599999987
        ratio: 12
        attack: 0.0500000007
        knee_type: soft
        knee_width: 3
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 4
        thresh: -22
        gate_thresh: -60
        release: 0.00499999989
        ratio: 12
        attack: 0.00300000003
        knee_type: soft
        knee_width: 3
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 5
        thresh: -22
        gate_thresh: -60
        release: 0.000500000024
        ratio: 12
        attack: 9.99999975e-05
        knee_type: soft
        knee_width: 3
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
lookahead_limiter:
  thresh: -9
  gate_thresh: -100
  release: 0.0399999991
  ratio: 1000
  attack: 0.00999999978
  knee_type: soft
  knee_width: 6
  idle_gain: 0
  makeup_gain_mode: manual
  makeup_gain: 3
clipper:
  enabled: true
  clip_level: 0.920000017