audio_devices:
  input:
    device_name: UNKNOWN
    device_id: 0
    device_uid: UNKNOWN
  output:
    device_name: UNKNOWN
    device_id: 0
    device_uid: UNKNOWN
input_gain:
  enabled: true
  L: 2.74658394
  R: 2.74658394
input_level:
  enabled: true
stereo_enhance:
  enabled: true
  drive: 1.26999998
agc_params:
  enabled: true
  mute_lo: false
  mute_hi: false
  drive: 6
  thresh: -14
  release_master: 7
  release_bass: 9
  gate_thresh: -28
  bass_coupling: 0.200000003
  window_size: -6
  window_release: 60
  ratio: 500
  bass_thresh: -14
  idle_gain: 0
  attack_master: 0.600000024
  attack_bass: 0.600000024
  bass_knee_type: soft
  bass_knee_width: 3
  master_knee_type: soft
  master_knee_width: 3
  bass_makeup_gain_mode: manual
  bass_makeup_gain: 0
  master_makeup_gain_mode: manual
  master_makeup_gain: 0
hf_enhance:
  enabled: false
multiband_crossover:
  enabled: true
multiband_params:
  enabled: true
  drive: 5
  gate_thresh: -60
  limiters_enabled: true
  master_post_gain: 7
  band1_solo: false
  band1_mute: false
  band2_solo: false
  band2_mute: false
  band3_solo: false
  band3_mute: false
  band4_solo: false
  band4_mute: false
  band5_solo: false
  band5_mute: false
  band1_comp_lim_offset: 0
  band2_comp_lim_offset: 0
  band3_comp_lim_offset: 0
  band4_comp_lim_offset: 0
  band5_comp_lim_offset: 0
  compressors:
    band1_compressor_enabled: true
    band2_compressor_enabled: true
    band3_compressor_enabled: true
    band4_compressor_enabled: true
    band5_compressor_enabled: true
    band34_coupling: 0.200000003
    band45_coupling: 0.200000003
    band32_coupling: 0.200000003
    band23_coupling: 0.200000003
    band21_coupling: 0.200000003
    bands:
      - band: 1
        thresh: -32
        gate_thresh: -60
        release: 0.140000001
        ratio: 1.60000002
        attack: 0.125
        knee_type: soft
        knee_width: 9
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 2
        thresh: -32
        gate_thresh: -60
        release: 0.109999999
        ratio: 1.79999995
        attack: 0.0900000036
        knee_type: soft
        knee_width: 9
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 3
        thresh: -32
        gate_thresh: -60
        release: 0.0799999982
        ratio: 1.79999995
        attack: 0.0599999987
        knee_type: soft
        knee_width: 9
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 4
        thresh: -32
        gate_thresh: -60
        release: 0.0599999987
        ratio: 1.79999995
        attack: 0.0399999991
        knee_type: soft
        knee_width: 9
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 5
        thresh: -30
        gate_thresh: -60
        release: 0.00079999998
        ratio: 1.79999995
        attack: 0.000500000024
        knee_type: soft
        knee_width: 9
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
  limiters:
    band1_limiter_enabled: true
    band2_limiter_enabled: true
    band3_limiter_enabled: true
    band4_limiter_enabled: true
    band5_limiter_enabled: true
    bands:
      - band: 1
        thresh: -23
        gate_thresh: -60
        release: 0.140000001
        ratio: 20
        attack: 0.125
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 2
        thresh: -23
        gate_thresh: -60
        release: 0.109999999
        ratio: 20
        attack: 0.0900000036
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 3
        thresh: -23
        gate_thresh: -60
        release: 0.0799999982
        ratio: 20
        attack: 0.0599999987
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 4
        thresh: -23
        gate_thresh: -60
        release: 0.0599999987
        ratio: 20
        attack: 0.0399999991
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
      - band: 5
        thresh: -23
        gate_thresh: -60
        release: 0.00079999998
        ratio: 20
        attack: 0.000500000024
        knee_type: soft
        knee_width: 6
        idle_gain: 0
        makeup_gain_mode: manual
        makeup_gain: 0
lookahead_limiter:
  thresh: -6
  gate_thresh: -100
  release: 0.0500000007
  ratio: 150
  attack: 0.0100000007
  knee_type: soft
  knee_width: 6
  idle_gain: 0
  makeup_gain_mode: manual
  makeup_gain: 0
clipper:
  enabled: true
  clip_level: 0.879999995
output_gain:
  enabled: true
  L: -2.24539518
  R: -2.24539518